-- KaziLink Supabase schema
-- Paste this directly into the Supabase SQL editor and run it.

create extension if not exists "pgcrypto";

create table if not exists public.users (
  id bigint generated by default as identity primary key,
  name text not null,
  email text not null unique,
  password text not null,
  role text not null default 'client' check (role in ('client', 'freelancer')),
  created_at timestamptz not null default now()
);

create table if not exists public.jobs (
  id bigint generated by default as identity primary key,
  title text not null,
  category text not null default 'General',
  budget text not null default 'KSh 10,000',
  location text not null default 'Nairobi',
  type text not null default 'Remote',
  description text not null default 'Project description pending.',
  deadline text not null default '7 days',
  applicants integer not null default 0,
  details text not null default 'Client is looking for a reliable professional.',
  posted text not null default 'Just now',
  created_at timestamptz not null default now()
);

-- Optional: enable row-level security if you want to lock it down later
-- alter table public.users enable row level security;
-- alter table public.jobs enable row level security;

-- Optional: simple public read policies for prototype use
-- create policy "Anyone can view users" on public.users for select using (true);
-- create policy "Anyone can view jobs" on public.jobs for select using (true);
-- create policy "Anyone can insert users" on public.users for insert with check (true);
-- create policy "Anyone can insert jobs" on public.jobs for insert with check (true);

-- Seed example rows
insert into public.users (name, email, password, role)
values
  ('Demo Client', 'demo@kazilink.co.ke', 'demo123', 'client'),
  ('Mercy Achieng', 'mercy@kazilink.co.ke', 'mercy123', 'freelancer')
on conflict (email) do nothing;

insert into public.jobs (title, category, budget, location, type, description, deadline, applicants, details, posted)
values
  (
    'Business Website Redesign',
    'Web Development',
    'KSh 35,000 - 55,000',
    'Nairobi',
    'Remote',
    'Need a modern, responsive business website for a growing retail brand.',
    '14 days',
    12,
    'We need a clean landing page, service sections, contact form, and analytics integration for our growing business in Nairobi.',
    '2 hours ago'
  ),
  (
    'Social Media Manager for Restaurant',
    'Social Media Management',
    'KSh 18,000 - 30,000',
    'Mombasa',
    'On-site',
    'We need content planning, ads support, and regular posting for 30 days.',
    '21 days',
    8,
    'The role includes weekly content ideas, branded captions, two reels per week, and basic engagement monitoring.',
    '5 hours ago'
  ),
  (
    'Plumber Needed for Kitchen Repair',
    'Plumbing',
    'KSh 12,000 - 20,000',
    'Kiambu',
    'On-site',
    'Fix leaking pipes, install a kitchen sink, and check mains pressure.',
    '3 days',
    16,
    'We need an experienced plumber to replace old piping and ensure all joints are watertight and compliant.',
    '1 day ago'
  )
on conflict do nothing;
